% compile matlab wrappers
disp('Building wrappers ...');
mex('../c/laserSlamMex.cpp',...
    '../c/icp/geometry2D.cpp',...
    '../c/icp/icp.cpp',...
    '../c/icp/nn.cpp',...
    '../c/robotics/ScanMatcher.cpp',...
    '../c/robotics/SensorModel.cpp',...
    '../c/robotics/GridMap.cpp',...
    '../c/robotics/slamWrapper.cpp',...
    '-I../c/icp',...
    '-I../c/robotics');
disp('...done!');
